# Tomcat
server:
  port: 9156
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  cache:
    type: redis
    redis:
      time-to-live: 20000 #毫秒
      cache-null-values: false #是否缓存空值
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    #password: 123  # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/greatseo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5  #\u521D\u59CB\u5EFA\u7ACB\u8FDE\u63A5\u6570\u91CF
      minIdle: 5  #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      maxActive: 20 #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maxWait: 10000  #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u6BEB\u79D2
      testOnBorrow: true #\u7533\u8BF7\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      timeBetweenEvictionRunsMillis: 60000 #\u914D\u7F6E\u95F4\u9694\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684\u65F6\u95F4\uFF08\u5355\u4F4D\u662F\u6BEB\u79D2\uFF09
      minEvictableIdleTimeMillis: 300000  #\u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09


